# Site settings
title: "En Route to Paradise Falls"
subtitle: "The Osler Family Travel Blog"
description: "Wanna take a trip? We'll tell you where we've been, maybe it will help. No Paradise Falls yet, need more balloons!"
baseurl: ""
url: "http://oslers.us/travel"
twitter_username: "Karenoia"
cruise_critic_username: "Boingy300"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
